config/routes.rb
SampleApp::Application.routes.draw do
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  root 'static_pages#home'
  match '/signup', to: 'users#new',  via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'
  match '/help', to: 'static_pages#help', via: 'get'
  match '/about', to: 'static_pages#about', via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  get 'search' => 'search#index', as: :search

end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
<ol class="microposts">
	<%= render partial: 'shared/feed_item', collection: @feed_items %>
</ol>
<%= will_paginate @feed_items %>
<% end %>

app/views/shared/_feed_item.html.erb
<li id="<%= feed_item.id %>">
	<%= link_to gravatar_for(feed_item.user), feed_item.user %>
	<span class="user">
		<%= link_to feed_item.user.name, feed_item.user %>
	</span>
	<span class="content"><%= feed_item.content %></span>
	<span class="timestamp">
		Posted <%= time_ago_in_words(feed_item.created_at) %> ago.
	</span>
	<% if current_user?(feed_item.user) %>
	<%= link_to "delete", feed_item, method: :delete, data: {confirm: "Are you sure?" }, title: feed_item.content %>
	<% end %>
</li>

app/views/shared/_home_no_signin.html.erb
<div class="center hero-unit">
<h1>Welcome to Tango Lingo! :)</h1>

<h2>
Welcome! Once you've signed in, you'll be able to chose your  <a href="http://www.hausland.pl">tutor</a>

</h2>

<%= link_to "Sign up now!",   signup_path, class: "btn btn-large btn-primary" %>

</div>

<%= link_to image_tag("Hausland Logo red small.png", alt: "Powered by Hausland"), 'http://www.hausland.pl/' %>

app/views/shared/_home_signin.html.erb
<div class="row">
	<aside class="span4">
		<section>
			<%= render 'shared/user_info' %>
		</section>
		<section>
			<%= render 'shared/stats' %>
		</section>
		<section>
			<%= render 'shared/micropost_form' %>
		</section>
	</aside>

	<div class="span8">
		<h3>Micropost Feed</h3>
		<%= render 'shared/feed' %>
	</div>

</div>

app/views/shared/_homer_no_signin.html.erb
<head>
  <style>
      @import url(http://fonts.googleapis.com/css?family=Roboto+Condensed:400,700);
      /* written by riliwan balogun http://www.facebook.com/riliwan.rabo*/
      .board{
          width: 75%;
          margin: 60px auto;
          height: 500px;
          background: #fff;
          /*box-shadow: 10px 10px #ccc,-10px 20px #ddd;*/
      }
      .board .nav-tabs {
          position: relative;
          /* border-bottom: 0; */
          /* width: 80%; */
          margin: 40px auto;
          margin-bottom: 0;
          box-sizing: border-box;

      }

      .board > div.board-inner{
          background: #fafafa url(http://subtlepatterns.com/patterns/geometry2.png);
          background-size: 30%;
      }

      p.narrow{
          width: 60%;
          margin: 10px auto;
      }

      .liner{
          height: 2px;
          background: #ddd;
          position: absolute;
          width: 80%;
          margin: 0 auto;
          left: 0;
          right: 0;
          top: 50%;
          z-index: 1;
      }

      .nav-tabs > li.active > a, .nav-tabs > li.active > a:hover, .nav-tabs > li.active > a:focus {
          color: #555555;
          cursor: default;
          /* background-color: #ffffff; */
          border: 0;
          border-bottom-color: transparent;
      }

      span.round-tabs{
          width: 70px;
          height: 70px;
          line-height: 70px;
          display: inline-block;
          border-radius: 100px;
          background: white;
          z-index: 2;
          position: absolute;
          left: 0;
          text-align: center;
          font-size: 25px;
      }

      span.round-tabs.one{
          color: rgb(34, 194, 34);border: 2px solid rgb(34, 194, 34);
      }

      li.active span.round-tabs.one{
          background: #fff !important;
          border: 2px solid #ddd;
          color: rgb(34, 194, 34);
      }

      span.round-tabs.two{
          color: #febe29;border: 2px solid #febe29;
      }

      li.active span.round-tabs.two{
          background: #fff !important;
          border: 2px solid #ddd;
          color: #febe29;
      }

      span.round-tabs.three{
          color: #3e5e9a;border: 2px solid #3e5e9a;
      }

      li.active span.round-tabs.three{
          background: #fff !important;
          border: 2px solid #ddd;
          color: #3e5e9a;
      }

      span.round-tabs.four{
          color: #f1685e;border: 2px solid #f1685e;
      }

      li.active span.round-tabs.four{
          background: #fff !important;
          border: 2px solid #ddd;
          color: #f1685e;
      }

      span.round-tabs.five{
          color: #999;border: 2px solid #999;
      }

      li.active span.round-tabs.five{
          background: #fff !important;
          border: 2px solid #ddd;
          color: #999;
      }

      .nav-tabs > li.active > a span.round-tabs{
          background: #fafafa;
      }
      .nav-tabs > li {
          width: 20%;
      }
      li.active:before {
          content: " ";
          position: absolute;
          left: 45%;
          opacity:0;
          margin: 0 auto;
          bottom: -2px;
          border: 10px solid transparent;
          border-bottom-color: #fff;
          z-index: 1;
          transition:0.2s ease-in-out;
      }
      li:after {
          content: " ";
          position: absolute;
          left: 45%;
          opacity:0;
          margin: 0 auto;
          bottom: 0px;
          border: 5px solid transparent;
          border-bottom-color: #ddd;
          transition:0.1s ease-in-out;

      }
      li.active:after {
          content: " ";
          position: absolute;
          left: 45%;
          opacity:1;
          margin: 0 auto;
          bottom: 0px;
          border: 10px solid transparent;
          border-bottom-color: #ddd;

      }
      .nav-tabs > li a{
          width: 70px;
          height: 70px;
          margin: 20px auto;
          border-radius: 100%;
          padding: 0;
      }

      .nav-tabs > li a:hover{
          background: transparent;
      }

      .tab-content{
      }
      .tab-pane{
          position: relative;
          padding-top: 50px;
      }
      .tab-content .head{
          font-family: 'Roboto Condensed', sans-serif;
          font-size: 25px;
          text-transform: uppercase;
          padding-bottom: 10px;
      }
      .btn-outline-rounded{
          padding: 10px 40px;
          margin: 20px 0;
          border: 2px solid transparent;
          border-radius: 25px;
      }

      .btn.green{
          background-color:#5cb85c;
          /*border: 2px solid #5cb85c;*/
          color: #ffffff;
      }


      @media( max-width : 585px ){

          .board {
              width: 90%;
              height:auto !important;
          }
          span.round-tabs {
              font-size:16px;
              width: 50px;
              height: 50px;
              line-height: 50px;
          }
          .tab-content .head{
              font-size:20px;
          }
          .nav-tabs > li a {
              width: 50px;
              height: 50px;
              line-height:50px;
          }

          li.active:after {
              content: " ";
              position: absolute;
              left: 35%;
          }

          .btn-outline-rounded {
              padding:12px 20px;
          }
      }


  </style>

  <script>

      $(function(){
          $('a[title]').tooltip();
      });

  </script>

</head>
<body>
<section style="background:#efefe9;">
  <div class="container">
    <div class="row">
      <div class="board">
        <!-- <h2>Welcome to IGHALO!<sup>™</sup></h2>-->
        <div class="board-inner">
          <ul class="nav nav-tabs" id="myTab">
            <div class="liner"></div>
            <li class="active">
              <a href="#home" data-toggle="tab" title="welcome">
                      <span class="round-tabs one">
                              <i class="glyphicon glyphicon-home"></i>
                      </span>
              </a></li>

            <li><a href="#profile" data-toggle="tab" title="profile">
                     <span class="round-tabs two">
                         <i class="glyphicon glyphicon-user"></i>
                     </span>
            </a>
            </li>
            <li><a href="#messages" data-toggle="tab" title="bootsnipp goodies">
                     <span class="round-tabs three">
                          <i class="glyphicon glyphicon-gift"></i>
                     </span> </a>
            </li>

            <li><a href="#settings" data-toggle="tab" title="blah blah">
                         <span class="round-tabs four">
                              <i class="glyphicon glyphicon-comment"></i>
                         </span>
            </a></li>

            <li><a href="#doner" data-toggle="tab" title="completed">
                         <span class="round-tabs five">
                              <i class="glyphicon glyphicon-ok"></i>
                         </span> </a>
            </li>

          </ul></div>

        <div class="tab-content">
          <div class="tab-pane fade in active" id="home">

            <h3 class="head text-center">Welcome to Bootsnipp<sup>™</sup> <span style="color:#f48260;">♥</span></h3>
            <p class="narrow text-center">
              Lorem ipsum dolor sit amet, his ea mollis fabellas principes. Quo mazim facilis tincidunt ut, utinam saperet facilisi an vim.
            </p>

            <p class="text-center">
              <a href="" class="btn btn-success btn-outline-rounded green"> start using bootsnipp <span style="margin-left:10px;" class="glyphicon glyphicon-send"></span></a>
            </p>
          </div>
          <div class="tab-pane fade" id="profile">
            <h3 class="head text-center">Create a Bootsnipp<sup>™</sup> Profile</h3>
            <p class="narrow text-center">
              Lorem ipsum dolor sit amet, his ea mollis fabellas principes. Quo mazim facilis tincidunt ut, utinam saperet facilisi an vim.
            </p>

            <p class="text-center">
              <a href="" class="btn btn-success btn-outline-rounded green"> create your profile <span style="margin-left:10px;" class="glyphicon glyphicon-send"></span></a>
            </p>

          </div>
          <div class="tab-pane fade" id="messages">
            <h3 class="head text-center">Bootsnipp goodies</h3>
            <p class="narrow text-center">
              Lorem ipsum dolor sit amet, his ea mollis fabellas principes. Quo mazim facilis tincidunt ut, utinam saperet facilisi an vim.
            </p>

            <p class="text-center">
              <a href="" class="btn btn-success btn-outline-rounded green"> start using bootsnipp <span style="margin-left:10px;" class="glyphicon glyphicon-send"></span></a>
            </p>
          </div>
          <div class="tab-pane fade" id="settings">
            <h3 class="head text-center">Drop comments!</h3>
            <p class="narrow text-center">
              Lorem ipsum dolor sit amet, his ea mollis fabellas principes. Quo mazim facilis tincidunt ut, utinam saperet facilisi an vim.
            </p>

            <p class="text-center">
              <a href="" class="btn btn-success btn-outline-rounded green"> start using bootsnipp <span style="margin-left:10px;" class="glyphicon glyphicon-send"></span></a>
            </p>
          </div>
          <div class="tab-pane fade" id="doner">
            <div class="text-center">
              <i class="img-intro icon-checkmark-circle"></i>
            </div>
            <h3 class="head text-center">thanks for staying tuned! <span style="color:#f48260;">♥</span> Bootstrap</h3>
            <p class="narrow text-center">
              Lorem ipsum dolor sit amet, his ea mollis fabellas principes. Quo mazim facilis tincidunt ut, utinam saperet facilisi an vim.
            </p>
          </div>
          <div class="clearfix"></div>
        </div>

      </div>
    </div>
  </div>
</section>


</body>

app/views/shared/_homex_no_signin.html.erb
<!DOCTYPE html>
<html lang="en">
<head>


  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css">

  <meta charset="utf-8">
  <title>Bootstrap 3, from LayoutIt!</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="">
  <meta name="author" content="">

  <!--link rel="stylesheet/less" href="less/bootstrap.less" type="text/css" /-->
  <!--link rel="stylesheet/less" href="less/responsive.less" type="text/css" /-->
  <!--script src="js/less-1.3.3.min.js"></script-->
  <!--append ‘#!watch’ to the browser URL, then refresh the page. -->

  <link href="css/bootstrap.min.css" rel="stylesheet">
  <link href="css/style.css" rel="stylesheet">

  <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
  <!--[if lt IE 9]>
  <script src="js/html5shiv.js"></script>
  <![endif]-->

  <!-- Fav and touch icons -->
  <link rel="apple-touch-icon-precomposed" sizes="144x144" href="img/apple-touch-icon-144-precomposed.png">
  <link rel="apple-touch-icon-precomposed" sizes="114x114" href="img/apple-touch-icon-114-precomposed.png">
  <link rel="apple-touch-icon-precomposed" sizes="72x72" href="img/apple-touch-icon-72-precomposed.png">
  <link rel="apple-touch-icon-precomposed" href="img/apple-touch-icon-57-precomposed.png">
  <link rel="shortcut icon" href="img/favicon.png">

  <script type="text/javascript" src="js/jquery.min.js"></script>
  <script type="text/javascript" src="js/bootstrap.min.js"></script>
  <script type="text/javascript" src="js/scripts.js"></script>

<style>

  .container {
      margin-top: 30px;
  }


  .jumbotron {
      margin-bottom: 40px;
  }


    body{background: #eee url(http://subtlepatterns.com/patterns/sativa.png);}
    html,body{
        position: relative;
        height: 100%;
    }
   table {
       margin-top: 50px;
   }

    .login-container{
        position: relative;
        width: 300px;
        margin: 80px auto;
        padding: 20px 40px 40px;
        text-align: center;
        background: #fff;
        border: 1px solid #ccc;
    }

    #output{
        position: absolute;
        width: 300px;
        top: -75px;
        left: 0;
        color: #fff;
    }

    #output.alert-success{
        background: rgb(25, 204, 25);
    }

    #output.alert-danger{
        background: rgb(228, 105, 105);
    }


    .login-container::before,.login-container::after{
        content: "";
        position: absolute;
        width: 100%;height: 100%;
        top: 3.5px;left: 0;
        background: #fff;
        z-index: -1;
        -webkit-transform: rotateZ(4deg);
        -moz-transform: rotateZ(4deg);
        -ms-transform: rotateZ(4deg);
        border: 1px solid #ccc;

    }

    .login-container::after{
        top: 5px;
        z-index: -2;
        -webkit-transform: rotateZ(-2deg);
        -moz-transform: rotateZ(-2deg);
        -ms-transform: rotateZ(-2deg);

    }

    .avatar{
        width: 100px;height: 100px;
        margin: 10px auto 30px;
        border-radius: 100%;
        border: 2px solid #aaa;
        background-size: cover;
    }

    .form-box input{
        width: 100%;
        padding: 10px;
        text-align: center;
        height:40px;
        border: 1px solid #ccc;;
        background: #fafafa;
        transition:0.2s ease-in-out;

    }

    .form-box input:focus{
        outline: 0;
        background: #eee;
    }

    .form-box input[type="text"]{
        border-radius: 5px 5px 0 0;
        text-transform: lowercase;
    }

    .form-box input[type="password"]{
        border-radius: 0 0 5px 5px;
        border-top: 0;
    }

    .form-box button.login{
        margin-top:15px;
        padding: 10px 20px;
    }

    .animated {
        -webkit-animation-duration: 1s;
        animation-duration: 1s;
        -webkit-animation-fill-mode: both;
        animation-fill-mode: both;
    }

    @-webkit-keyframes fadeInUp {
        0% {
            opacity: 0;
            -webkit-transform: translateY(20px);
            transform: translateY(20px);
        }

        100% {
            opacity: 1;
            -webkit-transform: translateY(0);
            transform: translateY(0);
        }
    }

    @keyframes fadeInUp {
        0% {
            opacity: 0;
            -webkit-transform: translateY(20px);
            -ms-transform: translateY(20px);
            transform: translateY(20px);
        }

        100% {
            opacity: 1;
            -webkit-transform: translateY(0);
            -ms-transform: translateY(0);
            transform: translateY(0);
        }
    }

    .fadeInUp {
        -webkit-animation-name: fadeInUp;
        animation-name: fadeInUp;
    }

</style>


<script>
    $(function(){
        var textfield = $("input[name=user]");
        $('button[type="submit"]').click(function(e) {
            e.preventDefault();
            //little validation just to check username
            if (textfield.val() != "") {
                //$("body").scrollTo("#output");
                $("#output").addClass("alert alert-success animated fadeInUp").html("Welcome back " + "<span style='text-transform:uppercase'>" + textfield.val() + "</span>");
                $("#output").removeClass(' alert-danger');
                $("input").css({
                    "height":"0",
                    "padding":"0",
                    "margin":"0",
                    "opacity":"0"
                });
                //change button text
                $('button[type="submit"]').html("continue")
                        .removeClass("btn-info")
                        .addClass("btn-default").click(function(){
                            $("input").css({
                                "height":"auto",
                                "padding":"10px",
                                "opacity":"1"
                            }).val("");
                        });

                //show avatar
                $(".avatar").css({
                    "background-image": "url('http://api.randomuser.me/0.3.2/portraits/women/35.jpg')"
                });
            } else {
                //remove success mesage replaced with error message
                $("#output").removeClass(' alert alert-success');
                $("#output").addClass("alert alert-danger animated fadeInUp").html("sorry enter a username ");
            }
            //console.log(textfield.val());

        });
    });


</script>



</head>

<body>

<div class="container">
  <div class="row clearfix">
    <div class="col-md-12 column">
      <div class="carousel slide" id="carousel-271490">
        <ol class="carousel-indicators">
          <li class="active" data-slide-to="0" data-target="#carousel-271490">
          </li>
          <li data-slide-to="1" data-target="#carousel-271490">
          </li>
          <li data-slide-to="2" data-target="#carousel-271490">
          </li>
        </ol>
        <div class="carousel-inner">
          <div class="item active">
            <img alt="" src="http://lorempixel.com/1600/500/sports/1" />
            <div class="carousel-caption">
              <h4>
                Arbil (24) from Mumbai, India
              </h4>
              <p>
                Arbil is a semi-professional cricket player by day. Did you know that he's also an awesome language teacher. Learn Hindi with Arbil and find out!
              </p>
            </div>
          </div>
          <div class="item">
            <img alt="" src="http://lorempixel.com/1600/500/sports/2" />
            <div class="carousel-caption">
              <h4>
                Sean (26) from Auckland, New Zealand
              </h4>
              <p>
                Sean's true love are the waves. When he gets of his board you can meet him at Tango Lingo. He'll help you navigate through English vocab like no other. Who knows, maybe he'll also teach you a thing or two about surfing?
              </p>
            </div>
          </div>
          <div class="item">
            <img alt="" src="http://lorempixel.com/1600/500/sports/3" />
            <div class="carousel-caption">
              <h4>
                Jurgen (32) from Aachen, Germany
              </h4>
              <p>
               Sprichst du Deutsch? If not, no problem. Jurgen, a semi-professional bike racer, will be happy to climb the peaks of German grammar with you. Are you up for the challenge? Es geht los!
              </p>
            </div>
          </div>
        </div> <a class="left carousel-control" href="#carousel-271490" data-slide="prev"><span class="glyphicon glyphicon-chevron-left"></span></a> <a class="right carousel-control" href="#carousel-271490" data-slide="next"><span class="glyphicon glyphicon-chevron-right"></span></a>
      </div>
    </div>
  </div>
</div>






<div class="container">
  <div class="row clearfix">
    <div class="col-md-12 column">
      <div class="jumbotron">
        <h1>
          Welcome to Tango Lingo!
        </h1>
        <p>
          We'll set you up with a new language tutor and have you chatting away in a foreign language in no time. We bring together those wishing to teach and those eager to learn. Dive in, we're sure you'll meet someone interesting to practice your language skills with :)
        </p>
        <p>
          <%= link_to "Learn more", about_path, class: "btn btn-primary btn-large" %>
          <%= link_to "Sign up now!",   signup_path, class: "btn btn-large btn-primary" %>
        </p>
      </div>
      <a id="modal-308157" href="#modal-container-308157" role="button" class="btn" data-toggle="modal">Would you like to teach?</a>

      <div class="modal fade" id="modal-container-308157" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
              <h4 class="modal-title" id="myModalLabel">
                Hi! Hola! Hallo! Czesc!
              </h4>
            </div>

            <div class="modal-body">
              We're happy you want to teach with TangoLingo! This option will be available soon.
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-default" data-dismiss="modal">Close</button> <button type="button" class="btn btn-primary">Save changes</button>
            </div>
          </div>

        </div>

      </div>

      <table class="table">
        <thead>
        <tr>
          <th>
            #
          </th>
          <th>
            Product
          </th>
          <th>
            Payment Taken
          </th>
          <th>
            Status
          </th>
        </tr>
        </thead>
        <tbody>
        <tr>
          <td>
            1
          </td>
          <td>
            TB - Monthly
          </td>
          <td>
            01/04/2012
          </td>
          <td>
            Default
          </td>
        </tr>
        <tr class="active">
          <td>
            1
          </td>
          <td>
            TB - Monthly
          </td>
          <td>
            01/04/2012
          </td>
          <td>
            Approved
          </td>
        </tr>
        <tr class="success">
          <td>
            2
          </td>
          <td>
            TB - Monthly
          </td>
          <td>
            02/04/2012
          </td>
          <td>
            Declined
          </td>
        </tr>
        <tr class="warning">
          <td>
            3
          </td>
          <td>
            TB - Monthly
          </td>
          <td>
            03/04/2012
          </td>
          <td>
            Pending
          </td>
        </tr>
        <tr class="danger">
          <td>
            4
          </td>
          <td>
            TB - Monthly
          </td>
          <td>
            04/04/2012
          </td>
          <td>
            Call in to confirm
          </td>
        </tr>
        </tbody>
      </table>
      <blockquote>
        <p>
          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere erat a ante.
        </p> <small>Someone famous <cite>Source Title</cite></small>
      </blockquote>
    </div>
  </div>
  <div class="container">
    <div class="row">
      <h2>Carousel Reviews</h2>
    </div>
  </div>

  <div class="row clearfix">
    <div class="col-md-4 column">
      <h2>
        Heading
      </h2>
      <p>
        Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui.
      </p>
      <p>
        <a class="btn" href="#">View details »</a>
      </p>
    </div>
    <div class="col-md-4 column">
      <h2>
        Heading
      </h2>
      <p>
        Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui.
      </p>
      <p>
        <a class="btn" href="#">View details »</a>
      </p>
    </div>
    <div class="col-md-4 column">
      <h2>
        Heading
      </h2>
      <p>
        Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui.
      </p>
      <p>
        <a class="btn" href="#">View details »</a>
      </p>
    </div>
  </div>
</div>

</body>
</html>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost) do |f| %>
<%= render "shared/error_messages", object: f.object %>
<div class="field">
	<%= f.text_area :content, placeholder: "compose new micropost..." %>
</div>
<%= f.submit "Post", class: "btn btn-large btn-primary" %>
<span class="countdown"></span>

<% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
	<a href="<%= following_user_path(@user) %>">
		<strong id="following" class="stat">
			<%= @user.followed_users.count %>
		</strong>
	following</a>
	<a href="<%= followers_user_path(@user) %>">
		<strong id="followers" class="stat">
			<%= @user.followers.count %>
		</strong>
	followers</a>
</div>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: 52), current_user %>
<h1>
	<%= current_user.name %>
</h1>
<span>
	<%= link_to "view my profile", current_user %>
</span>
<span>
	<%= pluralize(current_user.microposts.count, "micropost") %>
</span>